### ISSUE TITLE
Why ignore *.js and *.vue in .eslintignore ? 

### ISSUE THREAD

**Issue by dannyZhou** [yangzongzhuan/RuoYi-Vue#39]
https://github.com/yangzongzhuan/RuoYi-Vue/blob/81630a096f9c46b20138c609770575e5491bd623/ruoyi-ui/.eslintignore#L8

https://github.com/yangzongzhuan/RuoYi-Vue/blob/81630a096f9c46b20138c609770575e5491bd623/ruoyi-ui/.eslintignore#L10

**Comment by yangzongzhuan** [comment]
因为很多格式不是规范的，难免会有各种警告。

**Comment by dannyZhou** [comment]
处理方式不应该是 ignore ， 而是 写好一个 正确的 eslint 然后进行格式化
