### ISSUE TITLE
RateLimiterAspect触发限流后提示不正确

### ISSUE THREAD

**Issue by sukang00** [yangzongzhuan/RuoYi-Vue#43]
![image](https://user-images.githubusercontent.com/21122462/184819193-d915994a-5197-48ac-947b-892df98394f8.png)
try 里面  throw new ServiceException("访问过于频繁，请稍候再试"); 会被 外层catch (Exception e) 拦住，所以一直不提示 "访问过于频繁，请稍候再试"

**Comment by yangzongzhuan** [comment]
测试是正常有效的，没有你说的问题。上面还有一个catch会捕获ServiceException异常，而不是进入Exception
