### ISSUE TITLE
请问 User、Role这些实体，为什么放在common里面

### ISSUE THREAD

**Issue by wh2206** [yangzongzhuan/RuoYi-Vue#44]
![image](https://user-images.githubusercontent.com/60561780/188253275-62ccf43a-f0c2-4bad-ba5e-6ec2372dae04.png)

请问 User、Role这些实体，为什么放在common里面？不太好理解

**Comment by yangzongzhuan** [comment]
因为有些其他模块需要用到。属性通用实体
