### ISSUE TITLE
About node version

### ISSUE THREAD

**Issue by Johnson1103** [yangzongzhuan/RuoYi-Vue#50]
I use node version > 18.8.0
npm install 

it. 

up to date, audited 1603 packages in 1m

36 vulnerabilities (9 moderate, 19 high, 8 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by yangzongzhuan** [comment]
Node.js 版本需 >= 12 ，建议为 14.x或16x，不建议>=18版本。
