### ISSUE TITLE
图片不能回显（404 静态资源不能映射）

### ISSUE THREAD

**Issue by xieshizhou** [yangzongzhuan/RuoYi-Vue#59]
没有改任何文件上传下载路径的情况下，图片上传过后发送的get请求报404错误，请问需要改什么地方吗

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
