### ISSUE TITLE
项目启动后，其它浏览器都OK，Safari浏览器打开后不断的加载

### ISSUE THREAD

**Issue by yongahua** [yangzongzhuan/RuoYi-Vue#61]
Safari 5.1.7

ie，360，chrome，火狐这些浏览器都可以正常访问和使用，Safari浏览器打开就只有loading在不停的转
一开始提示sockjs-client问题，应该是ES6语法兼容问题，
![image](https://user-images.githubusercontent.com/28726820/236989737-33130dac-c4d9-4d14-ac74-c6eec6ee45a5.png)

然后我在vue.config.js中添加了transpileDependencies: ['sockjs-client'],
然后又有新的错误出现了！
这下我蒙了yntaxError: Cannot name a function proto chunk-vendors.js:4488S
当前框架部兼容Safari5.1.7吗？
![image](https://user-images.githubusercontent.com/28726820/236989795-d6855171-120c-466d-9246-897f45dca470.png)

**Comment by yongahua** [comment]
@yangzongzhuan 还请大神帮忙看一下

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
