### ISSUE TITLE
ruoyi不支持boolean类型数据显示

### ISSUE THREAD

**Issue by yida-lxw** [yangzongzhuan/RuoYi-Vue#62]
数据库表里有张表字段类型为bit类型，java里对应类型为boolean,
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/5f67f200-14e2-4a43-a96a-8119b9eaa956)
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/61fa68d7-0a9f-41a5-82d1-897591239982)
浏览器里按F12，可以看到后台已经正确返回json数据了，但是前端页面无法正确显示boolean类型数据，
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/ff7991eb-4340-490b-bef5-a455f82b215f)
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/d4216a22-a757-4224-85cb-9e05c00caa67)

但是如果尝试使用数据字典，打算将true/false转换为是否来展示，结果页面直接不显示数据了，整个表格为空了。
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/72038a18-8dc5-4e84-b098-4e96c32b585c)
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/5eb03e4b-4377-44a1-936e-3b3e626a3e24)
![image](https://github.com/yangzongzhuan/RuoYi-Vue/assets/12723117/30e355cd-5fa0-4828-b553-ada3842efaec)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
