### ISSUE TITLE
若依系统出现在线用户重复在线问题

### ISSUE THREAD

**Issue by mingpingyao** [yangzongzhuan/RuoYi-Vue#64]
![afa899de-28ee-4f83-afdc-4cf489298368](https://github.com/yangzongzhuan/RuoYi-Vue/assets/50660441/c63fb669-5aba-4d50-b3cb-ea9320b8e7de)

**Comment by mingpingyao** [comment]
请大佬帮忙看下

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
