### ISSUE TITLE
集成第三方登录回调有问题，不能通过request获取到当前绑定的用户信息

### ISSUE THREAD

**Issue by ZhongChunle** [yangzongzhuan/RuoYi-Vue#66]
<img width="1192" alt="图片" src="https://github.com/yangzongzhuan/RuoYi-Vue/assets/87836714/f698f230-497f-4cc2-b221-f7ee0734207f">
如果说先去查询数据库的话那么就没办法知道当前登录用户是谁并且绑定谁

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
