### ISSUE TITLE
导航栏的内容，如果过多，会超出屏幕，不能自动定位到当前页面的导航，且无法滚动，没有左右移动的按钮

### ISSUE THREAD

**Issue by wang-cola** [yangzongzhuan/RuoYi-Vue#8]
![image](https://user-images.githubusercontent.com/21015798/76942593-f3f18c00-6938-11ea-9502-7ee7ef9f71ac.png)

**Comment by wang-cola** [comment]
![image](https://user-images.githubusercontent.com/21015798/76942698-1e434980-6939-11ea-9c49-f19e5460f99f.png

**Comment by wang-cola** [comment]
![image](https://user-images.githubusercontent.com/21015798/76942850-5d719a80-6939-11ea-8d4f-8dec52c8bcce.png)

**Comment by yangzongzhuan** [comment]
试了下没有你说的问题，且有滚动。
![image](https://user-images.githubusercontent.com/19240310/83330076-801c1a00-a2bf-11ea-9c03-f07f92dd3cae.png)
