### ISSUE TITLE
怎么总爱报错啊？Uncaught SyntaxError: Invalid or unexpected token (at app.js:1709:6)

### ISSUE THREAD

**Issue by elarbor** [yangzongzhuan/RuoYi-Vue#93]
![image](https://github.com/user-attachments/assets/7d0ba07e-4ce5-4ca6-8cb3-66fdc422dc94)

**Comment by yangzongzhuan** [comment]
测试验证是有效的，没有你说的问题, 请提供出能复现问题详细描述和步骤。
